events {
    worker_connections 2048;
}

stream {
    upstream exam_servers {
        # Docker internal DNS akan otomatis membagi traffic ke semua replica exam-server
        server exam-server:9000;
    }

    server {
        listen 9000;
        proxy_pass exam_servers;
    }
}