# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grading_service/grading.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'grading_service/grading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgrading_service/grading.proto\x12\x07grading\"N\n\x0cGradeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bquestion_id\x18\x02 \x01(\x05\x12\x18\n\x10submitted_answer\x18\x03 \x01(\t\"D\n\rGradeResponse\x12\x12\n\nis_correct\x18\x01 \x01(\x08\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\t2T\n\x0eGradingService\x12\x42\n\x0fGradeSubmission\x12\x15.grading.GradeRequest\x1a\x16.grading.GradeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grading_service.grading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADEREQUEST']._serialized_start=42
  _globals['_GRADEREQUEST']._serialized_end=120
  _globals['_GRADERESPONSE']._serialized_start=122
  _globals['_GRADERESPONSE']._serialized_end=190
  _globals['_GRADINGSERVICE']._serialized_start=192
  _globals['_GRADINGSERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
